import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/lib/providers/ui/theme-provider";
import { AuthProvider } from "@/lib/providers/auth/auth-provider";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Next Starter Kit",
  description: "Generated by brandonkpbailey",
  openGraph: {
    description: "Build your next SaaS product",
    images: [""],
  },
  twitter: {
    card: "summary_large_image",
    title: "Next Starter Kit",
    description: "Build your next SaaS product.",
    siteId: "",
    creator: "@brandonkpbailey",
    creatorId: "",
    images: [""],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html className="scroll-smooth" lang="en" suppressHydrationWarning>
        <body
          className={`${GeistSans.variable} ${GeistMono.variable} font-regular`}
          // className={GeistSans.className} suppressHydrationWarning>
          suppressHydrationWarning
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
